// File generated by FlutterFire CLI.
// Run `dart run flutterfire configure` to replace with your project's config.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSy placeholder',
      appId: '1:000000000000:ios:placeholder',
      messagingSenderId: '000000000000',
      projectId: 'tapr-placeholder',
      storageBucket: 'tapr-placeholder.appspot.com',
      iosBundleId: 'com.tapr.app',
      androidClientId: '000000000000-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com',
    );
  }
}
