default_platform(:ios)

platform :ios do
  lane :beta do
    build_app(
      scheme: "Runner",
      export_method: "app-store-connect",
      output_directory: "./build",
      output_name: "Tapr.ipa"
    )
    upload_to_testflight
  end

  lane :release_ios do
    build_app(
      scheme: "Runner",
      export_method: "app-store-connect",
      output_directory: "./build",
      output_name: "Tapr.ipa"
    )
    upload_to_app_store(
      submit_for_review: false,
      automatic_release: false
    )
  end
end

platform :android do
  lane :release_android do
    supply(
      json_key_data: ENV["SUPPLY_JSON_KEY_DATA"],
      track: "internal"
    )
  end
end
